# Generated by Django 3.2.15 on 2023-05-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qa', '0001_initial'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmark_questions',
            field=models.ManyToManyField(blank=True, related_name='bookmark_questions', to='qa.Question'),
        ),
    ]
