# Generated by Django 3.2.15 on 2023-07-07 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquestion',
            name='page_element',
        ),
        migrations.RemoveField(
            model_name='question',
            name='page_element',
        ),
        migrations.AddField(
            model_name='page_element',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='page_element', to='qa.question'),
        ),
    ]
