# Generated by Django 3.2.15 on 2023-05-14 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('badge_type', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=30)),
                ('tag_name', models.CharField(default='', max_length=30)),
                ('preBuild', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bade_position', models.CharField(choices=[('TAG', 'Tag'), ('BADGE', 'Badge')], default='', max_length=30)),
                ('url', models.URLField(blank=True, null=True)),
                ('answerIf_TagOf_A', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.answer')),
            ],
        ),
    ]
