# Generated by Django 3.2.15 on 2023-05-14 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0002_initial'),
        ('tagbadge', '0004_auto_20220105_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagbadge',
            name='awarded_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tagbadge',
            name='questionIf_TagOf_Q',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.question'),
        ),
    ]
